; bed.g
; called to level the bed
;
; generated by RepRapFirmware Configuration Tool v3.5.10 on Mon Apr 28 2025 09:39:42 GMT-0400 (Eastern Daylight Time)
M201.1 X{global.linaccel} Y{global.linaccel} B{global.linaccel} C{global.linaccel} Z500		 ; reduce accel
M558 F200; configure unfiltered digital probe via slot #0
G1 X0 Y0 Z45 B0 C0 F{global.zspeed}


M564 S0
M561


;25mm offset in +x
M557 X-60:60 Y-60:60 P6 ;This is ignored but is a required ine

G29 S4 P"probePoints.csv"; call mesh bed compensation
G29

M564 S1