; homeall.g
; called to home all axes
;
; generated by RepRapFirmware Configuration Tool v3.5.10 on Mon Apr 28 2025 09:39:46 GMT-0400 (Eastern Daylight Time)

; increase Z
G91 ; relative positioning
G1 H2 Z15 F6000 ; move Z relative to current position to avoid dragging nozzle over the bed
G90 ; absolute positioning

; home XY
M98 P"homex.g"
M98 P"homey.g"
M98 P"homec.g"

M98 P"homez.g"
; home Z
; Step 1
;G1 B90 F3000

; Step 2: Probe Z using PINDA at center of bed
;var xCenter = move.compensation.probeGrid.mins[0] + (move.compensation.probeGrid.maxs[0] - move.compensation.probeGrid.mins[0]) / 2 - sensors.probes[0].offsets[0]
;var yCenter = move.compensation.probeGrid.mins[1] + (move.compensation.probeGrid.maxs[1] - move.compensation.probeGrid.mins[1]) / 2 - sensors.probes[0].offsets[1]
;G1 X{var.xCenter} Y{var.yCenter} F6000
;G30

; Step 3: Raise Z 15mm and rotate B back
;G91
;G1 Z25 F300
;G90
;G1 B0 F3000              ; Rotate B 90° counterclockwise (back to B=0)

; Done
M118 L1 P0 S"Homing complete"
