; homex.g
; called to home the X axis. Also homes B since they are co-dependent
;
; generated by RepRapFirmware Configuration Tool v3.5.10 on Mon Apr 28 2025 09:39:46 GMT-0400 (Eastern Daylight Time)


G90 												; back to absolute positioning
M400										 ; wait again
M913 X100 					 ; motor currents back to 100%
M201 X1000			 ; accel back to original 
M915 S63 X B R0					 ; Disable Logging and lower stall detection

M400 						; wait til stuff stops
M574 X1 S3 			  ; use stall guard for endstops

M913 X50  		; drop motor currents to 50% 
M201 X500 B500	 ; reduce acceleration on X/Y to stop false triggers
 
M915 X S60 R0 F1 H200	;  Sensitivity 4, don’t take action, don’t filter, 400steps/sec
G91 											; set relative
G1 H1 X200 F3000			 ; move left 250mm, stopping at the endstop
M400

; time to home b as well

M569 P0.0 S0 D3 V100 ; flips the motor
G1 H1 X200 F3000			 ; rotate
G92 B-45.0

; back to normal control

M569 P0.0 S1 D3 V100 ; driver 0.0 goes forwards (XB axis)

G1 B0 F2000 ;move done here to be happy
G92 X84.1
G90 												; back to absolute positioning
M400										 ; wait again
M913 X100 					 ; motor currents back to 100%
M201 X1000 B1000 			 ; accel back to original 
M915 S63 X B R0					 ; Disable Logging and lower stall detection
G1 X0 B0 F5000							; move away from end
