; pause.g
; called to retract a physical Z probe
;
; generated by RepRapFirmware Configuration Tool v3.5.10 on Mon Apr 28 2025 09:39:46 GMT-0400 (Eastern Daylight Time)


G4 P500
;G10

G1 X0 Y0 Z5 F{global.zspeed}	 R1 ; go to 5mm above position of the last move
;G90 ; absolute positioning
;G1 X90 Y0 Z140 B90 C0 F1500; go to X=0 Y=0 Z100
