; pause.g
; called to retract a physical Z probe
;
; generated by RepRapFirmware Configuration Tool v3.5.10 on Mon Apr 28 2025 09:39:46 GMT-0400 (Eastern Daylight Time)

G10
G91 ; relative positioning
G1 Z20 F1500 ; lift Z by 5mm
G90 ; absolute positioning
G1 X80 Y0 Z140 B90 C0 F1000; go to X=0 Y=0 Z100
