; resume.g
; called to retract a physical Z probe
;
; generated by RepRapFirmware Configuration Tool v3.5.10 on Mon Apr 28 2025 09:39:46 GMT-0400 (Eastern Daylight Time)

G11
M98 P"wipe.g"
G1 X0 Y0 Z5 F10500 R1 ; go to 5mm above position of the last move
G1 X0 Y0 Z0 F10500 R1; go back to the last print move
