; resume.g
; called to retract a physical Z probe
;
; generated by RepRapFirmware Configuration Tool v3.5.10 on Mon Apr 28 2025 09:39:46 GMT-0400 (Eastern Daylight Time)
G1 R1 X0 Y0 Z5 F1000 ; go to 5mm above position of the last move
G1 R1 X0 Y0 Z0 ; go back to the last print move
M83 ; relative extruder moves
G1 E100 F1000 ; extrude 100mm of filament
