; tpost0.g
; called after tool 0 has been selected
;
; generated by RepRapFirmware Configuration Tool v3.5.10 on Mon Apr 28 2025 09:39:46 GMT-0400 (Eastern Daylight Time)

M116 P0 ; wait for tool temperatures to be reached
